language: python
sudo: required
env:
  global:
    - CONAN_UPLOAD: 1
    - CONAN_REFERENCE: "FakeIt/2.0.2"
    - CONAN_USERNAME: "hinrikg"
    - CONAN_CHANNEL: "stable"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kalakris-cmake
    packages:
      - g++-4.8
      - cmake

install:
  - export CC='gcc-4.8'
  - export CXX='g++-4.8'

  # install Conan and associated package tools
  - pip install conan_package_tools

  # initialize the local conan repository
  - conan user

script:
  - python build.py
