language: python
sudo: required
env:
  global:
    - CONAN_UPLOAD: 1
    - CONAN_REFERENCE: "FakeIt/2.0.2"
    - CONAN_USERNAME: "hinrikg"
    - CONAN_CHANNEL: "stable"
compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:kalakris/cmake -y
  - sudo apt-get update -qq

  # upgrade GCC
  - sudo apt-get install g++-4.9 -y
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90

  # upgrade CMake
  - sudo apt-get install cmake -y

install:
  # install Conan and associated package tools
  - pip install conan_package_tools

  # initialize the local conan repository
  - conan user

script:
  - python build.py
